import { NextResponse } from "next/server"

export async function GET() {
  const data = [
    {
      id: "1",
      heroTitle: "OPTI 2024",
      heroDescription: "Programa básico de educación financiera",
      videoId: "1091240808",
      courseDate: "SÁBADO 15 DE ABRIL, 2024",
      courseTime: "09:00 AM - 05:00 PM",
      courseAges: "Edades: 16+ años",
      courseLocation: "Centro OPTI",
      whatsappUrl: "https://wa.me/1234567890",
      learningTitle: "¿Qué aprenderás?",
      learningItems: ["Conceptos básicos", "Ahorro", "Inversión"],
      icon1Title: "Educación",
      icon2Title: "Práctica",
      icon3Title: "Resultados",
      icon1Image: "/placeholder.svg?height=80&width=80",
      icon2Image: "/placeholder.svg?height=80&width=80",
      icon3Image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "2",
      heroTitle: "OPTIKIDS Escuela",
      heroDescription: "Programa para niños",
      videoId: "1091240808",
      courseDate: "SÁBADO 10 DE MAYO, 2024",
      courseTime: "10:00 AM - 04:00 PM",
      courseAges: "Edades: 7 a 9 años",
      courseLocation: "Escuela OPTIKIDS",
      whatsappUrl: "https://wa.me/1234567890",
      learningTitle: "¿Qué aprenderás?",
      learningItems: ["Dinero básico", "Juegos", "Emprendimiento"],
      icon1Title: "Diversión",
      icon2Title: "Aprendizaje",
      icon3Title: "Crecimiento",
      icon1Image: "/placeholder.svg?height=80&width=80",
      icon2Image: "/placeholder.svg?height=80&width=80",
      icon3Image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "3",
      heroTitle: "OPTI KIDS",
      heroDescription: "Programa de emprendimiento",
      videoId: "1091240808",
      courseDate: "DOMINGO 20 DE MAYO, 2024",
      courseTime: "09:00 AM - 06:00 PM",
      courseAges: "Edades: 10 a 15 años",
      courseLocation: "Campus OPTI KIDS",
      whatsappUrl: "https://wa.me/1234567890",
      learningTitle: "¿Qué aprenderás?",
      learningItems: ["Liderazgo", "Negocios", "Presentaciones"],
      icon1Title: "Liderazgo",
      icon2Title: "Innovación",
      icon3Title: "Éxito",
      icon1Image: "/placeholder.svg?height=80&width=80",
      icon2Image: "/placeholder.svg?height=80&width=80",
      icon3Image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "4",
      heroTitle: "OPTI AVANZADO",
      heroDescription: "Programa especializado",
      videoId: "1091240808",
      courseDate: "VIERNES 25 DE JUNIO, 2024",
      courseTime: "02:00 PM - 08:00 PM",
      courseAges: "Edades: 16+ años",
      courseLocation: "Centro Avanzado",
      whatsappUrl: "https://wa.me/1234567890",
      learningTitle: "¿Qué aprenderás?",
      learningItems: ["Análisis", "Inversión", "Marketing"],
      icon1Title: "Estrategia",
      icon2Title: "Análisis",
      icon3Title: "Networking",
      icon1Image: "/placeholder.svg?height=80&width=80",
      icon2Image: "/placeholder.svg?height=80&width=80",
      icon3Image: "/placeholder.svg?height=80&width=80",
    },
    {
      id: "5",
      heroTitle: "OPTI PREMIUM",
      heroDescription: "Programa exclusivo",
      videoId: "1091240808",
      courseDate: "SÁBADO 30 DE JULIO, 2024",
      courseTime: "08:00 AM - 06:00 PM",
      courseAges: "Edades: 18+ años",
      courseLocation: "Campus Premium",
      whatsappUrl: "https://wa.me/1234567890",
      learningTitle: "¿Qué aprenderás?",
      learningItems: ["Mentoría", "Casos reales", "Contactos"],
      icon1Title: "Mentoría",
      icon2Title: "Certificación",
      icon3Title: "Exclusividad",
      icon1Image: "/placeholder.svg?height=80&width=80",
      icon2Image: "/placeholder.svg?height=80&width=80",
      icon3Image: "/placeholder.svg?height=80&width=80",
    },
  ]

  return NextResponse.json(data)
}

export async function POST() {
  return NextResponse.json({ success: true })
}
